# Generated by Django 5.2.11 on 2026-02-20 11:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('category', models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('commute', 'Commute'), ('grocery', 'Grocery'), ('utility', 'Utility'), ('wear', 'Wear'), ('cosmetic', 'Cosmetic'), ('fun', 'Fun & Snack')], default='food', max_length=10)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
