# Generated by Django 5.2.11 on 2026-03-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingitem',
            name='is_done',
        ),
    ]
