# Generated by Django 5.2.11 on 2026-05-19 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_deposit_date_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savinggoal',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='purpose',
        ),
        migrations.AddField(
            model_name='savingwithdrawal',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.savinggoal'),
        ),
    ]
