# Generated by Django 5.2.11 on 2026-02-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='data',
            new_name='date',
        ),
    ]
