# Generated by Django 5.2.11 on 2026-02-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_rename_data_deposit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
